# Generated by Django 3.2.6 on 2022-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0002_alter_cars_kilometers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='icon',
        ),
        migrations.AddField(
            model_name='cartype',
            name='image',
            field=models.ImageField(blank=True, upload_to='cartypes'),
        ),
    ]
