# Generated by Django 3.2.6 on 2022-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0003_auto_20220502_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
