# Generated by Django 3.2.6 on 2022-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0004_cartype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='image',
            field=models.ImageField(blank=True, upload_to='cartype'),
        ),
    ]
