# Generated by Django 3.2.6 on 2022-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0005_alter_cartype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
