# Generated by Django 3.2.6 on 2022-05-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestdealapp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='registration_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, unique=True)),
                ('car_company', models.CharField(blank=True, max_length=50, null=True)),
                ('car_model', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_year', models.CharField(blank=True, max_length=10, null=True)),
                ('kilometers', models.CharField(blank=True, max_length=10, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=10, null=True)),
                ('mileage', models.CharField(blank=True, max_length=10, null=True)),
                ('transmission', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('car_discription', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestdealapp.cartype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ads Table',
            },
        ),
    ]
