# Generated by Django 3.2.6 on 2022-05-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0009_auto_20220507_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
        migrations.AlterField(
            model_name='cars',
            name='kilometers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
