# Generated by Django 3.2.6 on 2022-05-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0010_auto_20220508_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image',
        ),
    ]
