# Generated by Django 3.2.6 on 2022-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0011_remove_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
