# Generated by Django 3.2.6 on 2022-05-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0012_alter_cars_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='cartype',
            new_name='bodytype',
        ),
    ]
