# Generated by Django 3.2.6 on 2022-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0015_auto_20220508_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cars',
        ),
    ]
