# Generated by Django 3.2.6 on 2022-05-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0017_alter_ads_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='car_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bestdealapp.profile'),
        ),
    ]
