# Generated by Django 3.2.6 on 2022-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0018_auto_20220508_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='car_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
