# Generated by Django 3.2.6 on 2022-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0019_alter_ads_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='seller',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
