# Generated by Django 3.2.6 on 2022-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0020_alter_ads_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='car_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='seller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
