# Generated by Django 3.2.6 on 2022-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0021_auto_20220508_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='car_adds'),
        ),
    ]
