# Generated by Django 3.2.6 on 2022-05-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0024_ads_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bestdealapp.profile'),
        ),
    ]
