# Generated by Django 3.2.6 on 2022-05-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestdealapp', '0027_conatact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conatact_number',
            options={'verbose_name_plural': 'Contact Table'},
        ),
    ]
